[package]
name = "lambda-proto"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.16"
runtime = "0.3.0-alpha.4"
http = "0.1.17"
