[package]
name = "lambda"
version = "0.1.0"
authors = ["David Barsky <dbarsky@amazon.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.16"
runtime = "0.3.0-alpha.5"
http = "0.1.17"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
hyper = "0.12"
proptest = "0.9.3"
headers = "0.2.1"
lazy_static = "1.3.0"
bytes = "0.4.12"
lambda-attributes = { path = "../lambda-attributes", version = "0.1.0" }
pin-utils = "0.1.0-alpha.4"

[dev-dependencies]
trybuild = "1"
better-panic = "0.1.1"
